{
 "title": "Chaos Mesh Overview",
 "description": "Overview for monitoring Chaos Mesh. \n\nProviding active chaos experiments, instances of each components, and experiments activity events. ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Namespace", "label": "Chaos Mesh Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Chaos Experiments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Experiments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaos_dashboard_archived_experiments{namespace=\"$Namespace\", job=\"chaos_mesh_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schedules",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chaos_controller_manager_chaos_schedules)",
     "legendFormat": "Workflow"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chaos_controller_manager_chaos_workflows{namespace=\"$Namespace\", pod=\"$ControllerManager\"})",
     "legendFormat": "Workflow"
    }
   ]
  },
  {
   "title": "Experiments Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(type) (chaos_dashboard_archived_experiments{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Chaos Mesh Activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Experiments Events",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaos_controller_manager_emitted_event_total{namespace=\"$Namespace\", instance=~\"chaos-mesh-manager-metrics.*\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "Chaos Mesh Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Controller Manager Instances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(up{job=\"chaos_mesh_metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chaos Daemon Instances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 21 },
   "targets": [
    {
     "expr": "sum by(__name__) (up{job=\"chaos_mesh_metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chaos Dashboard Instances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 21 },
   "targets": [
    { "expr": "sum by(__name__) (up)", "legendFormat": "__auto" }
   ]
  }
 ]
}